apiVersion: apps/v1
kind: Deployment
metadata:
  name: europe-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: europe-website
  template:
    metadata:
      labels:
        app: europe-website
    spec:
      containers:
      - name: europe-website
        image: gcr.io/proyecto-gcp-test/europe-website
        ports:
        - containerPort: 80
